
import java.sql.*;
import Project.ConnectionProvider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hinab
 */
import javax.swing.JOptionPane;

public class delete_Product extends javax.swing.JFrame {

    /**
     * Creates new form delete_Buyer
     */
    public delete_Product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delete_product_ani = new javax.swing.JLabel();
        delete_product_icon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        search_productid = new javax.swing.JLabel();
        search_id = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        pname = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        activate = new javax.swing.JLabel();
        pname_text = new javax.swing.JTextField();
        rate_text = new javax.swing.JTextField();
        description_text = new javax.swing.JTextField();
        activate_text = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete_product_ani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete product ani.gif"))); // NOI18N
        getContentPane().add(delete_product_ani, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 270, -1));

        delete_product_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete product.png"))); // NOI18N
        getContentPane().add(delete_product_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 588, 20));

        search_productid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_productid.setText("Product ID");
        getContentPane().add(search_productid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        search_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_idActionPerformed(evt);
            }
        });
        getContentPane().add(search_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 197, -1));

        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 588, 10));

        pname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pname.setText("Product Name");
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        rate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rate.setText("Rate");
        getContentPane().add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        description.setText("Description");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        activate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activate.setText("Activate");
        getContentPane().add(activate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        pname_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(pname_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 224, -1));

        rate_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(rate_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 224, -1));

        description_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(description_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 224, -1));

        activate_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activate_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activate_textActionPerformed(evt);
            }
        });
        getContentPane().add(activate_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 224, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 588, 30));

        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all page background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_idActionPerformed

    private void activate_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activate_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activate_textActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new delete_Product().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String pId = search_id.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from product where pId='" + pId + "'");
            if (rs.next()) {
                pname_text.setText(rs.getString(2));
                rate_text.setText(rs.getString(3));
                description_text.setText(rs.getString(4));
                activate_text.setText(rs.getString(5));
                search_id.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "Product ID does not Exist");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String pId = search_id.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                st.executeUpdate("delete from product where pId='" + pId + "'");
                setVisible(false);
                new delete_Product().setVisible(true);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_Buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_Buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_Buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_Buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activate;
    private javax.swing.JTextField activate_text;
    private javax.swing.JLabel background;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JLabel delete_product_ani;
    private javax.swing.JLabel delete_product_icon;
    private javax.swing.JLabel description;
    private javax.swing.JTextField description_text;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel pname;
    private javax.swing.JTextField pname_text;
    private javax.swing.JLabel rate;
    private javax.swing.JTextField rate_text;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_id;
    private javax.swing.JLabel search_productid;
    // End of variables declaration//GEN-END:variables
}
