
import java.awt.Color;
import java.sql.*;
import Project.ConnectionProvider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hinab
 */
import java.awt.Color;
import javax.swing.JOptionPane;

public class new_Product extends javax.swing.JFrame {

    /**
     * Creates new form new_Product
     */
    public new_Product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        new_product_icon = new javax.swing.JLabel();
        new_product_ani = new javax.swing.JLabel();
        productid = new javax.swing.JLabel();
        productid_text = new javax.swing.JLabel();
        productname = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        activate = new javax.swing.JLabel();
        productname_text = new javax.swing.JTextField();
        rate_text = new javax.swing.JTextField();
        description_text = new javax.swing.JTextField();
        activate_combo = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        new_product_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        getContentPane().add(new_product_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        new_product_ani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New Product ani.gif"))); // NOI18N
        getContentPane().add(new_product_ani, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 249, -1));

        productid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        productid.setText("Product ID");
        getContentPane().add(productid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        productid_text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        productid_text.setForeground(new java.awt.Color(255, 0, 0));
        productid_text.setText("100");
        getContentPane().add(productid_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 110, -1, -1));

        productname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productname.setText("Product Name");
        getContentPane().add(productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 181, 98, -1));

        rate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rate.setText("Rate");
        getContentPane().add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 235, 98, -1));

        description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        description.setText("Description");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 286, 98, -1));

        activate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activate.setText("Activate");
        getContentPane().add(activate, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 337, 98, -1));

        productname_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productname_text.setForeground(new java.awt.Color(153, 153, 153));
        productname_text.setText("Enter Product Name");
        productname_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productname_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                productname_textFocusLost(evt);
            }
        });
        getContentPane().add(productname_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 181, 218, -1));

        rate_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rate_text.setForeground(new java.awt.Color(153, 153, 153));
        rate_text.setText("Enter Rate");
        rate_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rate_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rate_textFocusLost(evt);
            }
        });
        getContentPane().add(rate_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 232, 218, -1));

        description_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        description_text.setForeground(new java.awt.Color(153, 153, 153));
        description_text.setText("Enter Description");
        description_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                description_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                description_textFocusLost(evt);
            }
        });
        getContentPane().add(description_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 283, 218, -1));

        activate_combo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activate_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        getContentPane().add(activate_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 334, 218, -1));

        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 394, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 394, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 394, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 160, 588, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 378, 594, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, 588, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all page background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("select max(pId) from product");
            if (rs.first()) {
                int id = rs.getInt(1);
                id = id + 1;
                String str = String.valueOf(id);
                productid_text.setText(str);
            } else {
                productid_text.setText("1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void productname_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productname_textFocusGained
        // TODO add your handling code here:
        if (productname_text.getText().equals("Enter Product Name")) {
            productname_text.setText("");
            productname_text.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_productname_textFocusGained

    private void productname_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productname_textFocusLost
        // TODO add your handling code here:
        if (productname_text.getText().equals("")) {
            productname_text.setText("Enter Product Name");
            productname_text.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_productname_textFocusLost

    private void rate_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rate_textFocusGained
        // TODO add your handling code here:
        if (rate_text.getText().equals("Enter Rate")) {
            rate_text.setText("");
            rate_text.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_rate_textFocusGained

    private void rate_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rate_textFocusLost
        // TODO add your handling code here:
        if (rate_text.getText().equals("")) {
            rate_text.setText("Enter Rate");
            rate_text.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_rate_textFocusLost

    private void description_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_description_textFocusGained
        // TODO add your handling code here:
        if (description_text.getText().equals("Enter Description")) {
            description_text.setText("");
            description_text.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_description_textFocusGained

    private void description_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_description_textFocusLost
        // TODO add your handling code here:
        if (description_text.getText().equals("")) {
            description_text.setText("Enter Description");
            description_text.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_description_textFocusLost

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new new_Product().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String pId = productid_text.getText();
        String pName = productname_text.getText();
        String rate = rate_text.getText();
        String description = description_text.getText();
        String activate = (String) activate_combo.getSelectedItem();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into product values('" + pId + "','" + pName + "','" + rate + "','" + description + "','" + activate + "')");
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new new_Product().setVisible(true);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activate;
    private javax.swing.JComboBox<String> activate_combo;
    private javax.swing.JLabel background;
    private javax.swing.JButton close;
    private javax.swing.JLabel description;
    private javax.swing.JTextField description_text;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel new_product_ani;
    private javax.swing.JLabel new_product_icon;
    private javax.swing.JLabel productid;
    private javax.swing.JLabel productid_text;
    private javax.swing.JLabel productname;
    private javax.swing.JTextField productname_text;
    private javax.swing.JLabel rate;
    private javax.swing.JTextField rate_text;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
