
import java.awt.Color;
import Project.ConnectionProvider;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hinab
 */
import javax.swing.JOptionPane;

public class new_Buyer extends javax.swing.JFrame {

    /**
     * Creates new form new_Buyer
     */
    public new_Buyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        new_buyer_label = new javax.swing.JLabel();
        new_buyer_icon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        name = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        contact_text = new javax.swing.JTextField();
        email_text = new javax.swing.JTextField();
        address_text = new javax.swing.JTextField();
        gender_box = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        new_buyer_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New buyer ani.gif"))); // NOI18N
        getContentPane().add(new_buyer_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 27, 232, -1));

        new_buyer_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new buyer.png"))); // NOI18N
        getContentPane().add(new_buyer_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, 597, 10));

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 127, -1, -1));

        contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact.setText("Contact No.");
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 168, -1, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setText("E-mail");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 212, -1, -1));

        address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        address.setText("Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 256, -1, -1));

        gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 300, -1, -1));

        name_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name_text.setForeground(new java.awt.Color(153, 153, 153));
        name_text.setText("Enter your name");
        name_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_textFocusLost(evt);
            }
        });
        getContentPane().add(name_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 121, 240, -1));

        contact_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact_text.setForeground(new java.awt.Color(153, 153, 153));
        contact_text.setText("Enter your contact no.");
        contact_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contact_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contact_textFocusLost(evt);
            }
        });
        getContentPane().add(contact_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 165, 240, -1));

        email_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email_text.setForeground(new java.awt.Color(153, 153, 153));
        email_text.setText("Enter your e-mail");
        email_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_textFocusLost(evt);
            }
        });
        getContentPane().add(email_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 209, 240, -1));

        address_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        address_text.setForeground(new java.awt.Color(153, 153, 153));
        address_text.setText("Enter your address");
        address_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                address_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                address_textFocusLost(evt);
            }
        });
        getContentPane().add(address_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 253, 240, -1));

        gender_box.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gender_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(gender_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 297, 240, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 348, 597, 10));

        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 376, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 376, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 376, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all page background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_textFocusLost
        // TODO add your handling code here:
        if (name_text.getText().equals("")) {
            name_text.setText("Enter your name");
            name_text.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_name_textFocusLost

    private void name_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_textFocusGained
        // TODO add your handling code here:
        if (name_text.getText().equals("Enter your name")) {
            name_text.setText("");
            name_text.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_name_textFocusGained

    private void contact_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contact_textFocusGained
        // TODO add your handling code here:
        if (contact_text.getText().equals("Enter your contact no.")) {
            contact_text.setText("");
            contact_text.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_contact_textFocusGained

    private void contact_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contact_textFocusLost
        // TODO add your handling code here:
        if (contact_text.getText().equals("")) {
            contact_text.setText("Enter your contact no.");
            contact_text.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_contact_textFocusLost

    private void email_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_textFocusGained
        // TODO add your handling code here:
        if (email_text.getText().equals("Enter your e-mail")) {
            email_text.setText("");
            email_text.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_email_textFocusGained

    private void email_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_textFocusLost
        // TODO add your handling code here:
        if (email_text.getText().equals("")) {
            email_text.setText("Enter your e-mail");
            email_text.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_email_textFocusLost

    private void address_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_textFocusGained
        // TODO add your handling code here:
        if (address_text.getText().equals("Enter your address")) {
            address_text.setText("");
            address_text.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_address_textFocusGained

    private void address_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_textFocusLost
        // TODO add your handling code here:
        if (address_text.getText().equals("")) {
            address_text.setText("Enter your address");
            address_text.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_address_textFocusLost

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new new_Buyer().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String name = name_text.getText();
        String contactNo = contact_text.getText();
        String email = email_text.getText();
        String address = address_text.getText();
        String gender = (String) gender_box.getSelectedItem();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into buyer values('" + name + "','" + contactNo + "','" + email + "','" + address + "','" + gender + "')");
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new new_Buyer().setVisible(true);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Mobile Number already exists.");
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_Buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_Buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_Buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_Buyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_Buyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField address_text;
    private javax.swing.JLabel background;
    private javax.swing.JButton close;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField contact_text;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_text;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> gender_box;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel new_buyer_icon;
    private javax.swing.JLabel new_buyer_label;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
