
import java.sql.*;
import Project.ConnectionProvider;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import com.itextpdf.text.Document;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hinab
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class billing extends javax.swing.JFrame {

    public int finalTotal = 0;

    /**
     * Creates new form billing
     */
    public billing() {
        initComponents();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        datei.setText(dFormat.format(date));

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        timei.setText(dtf.format(now));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billing_icon = new javax.swing.JLabel();
        billing_ani = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        time_label = new javax.swing.JLabel();
        datei = new javax.swing.JLabel();
        timei = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buyer_details = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        contact = new javax.swing.JLabel();
        contact_input = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        address_input = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        product_details = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        pid_input = new javax.swing.JTextField();
        pname = new javax.swing.JLabel();
        pname_input = new javax.swing.JTextField();
        rate = new javax.swing.JLabel();
        rate_input = new javax.swing.JTextField();
        quantity = new javax.swing.JLabel();
        quantity_input = new javax.swing.JTextField();
        description = new javax.swing.JLabel();
        description_input = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        billing_table = new javax.swing.JTable();
        calculation = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        paid_amount = new javax.swing.JLabel();
        return_amount = new javax.swing.JLabel();
        total_input = new javax.swing.JTextField();
        paid_input = new javax.swing.JTextField();
        return_input = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 150));
        setMaximumSize(new java.awt.Dimension(1164, 550));
        setMinimumSize(new java.awt.Dimension(1164, 550));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billing_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing frame.png"))); // NOI18N
        getContentPane().add(billing_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, -1, -1));

        billing_ani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Billing ani.gif"))); // NOI18N
        getContentPane().add(billing_ani, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 15, -1, 90));

        date_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date_label.setText("Date:");
        getContentPane().add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 25, -1, -1));

        time_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        time_label.setText("Time:");
        getContentPane().add(time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 73, -1, -1));

        datei.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        datei.setText("jLabel5");
        getContentPane().add(datei, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 25, -1, -1));

        timei.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        timei.setText("jLabel6");
        getContentPane().add(timei, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 73, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, 1152, -1));

        buyer_details.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buyer_details.setText("Buyer Details:");
        getContentPane().add(buyer_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, -1, -1));

        name_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });
        getContentPane().add(name_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 169, 180, -1));

        contact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact.setText("Contact No.");
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 172, -1, -1));

        contact_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contact_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_inputActionPerformed(evt);
            }
        });
        getContentPane().add(contact_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 169, 181, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email.setText("E-mail");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 172, -1, -1));

        email_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(email_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 169, 180, -1));

        address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        address.setText("Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 172, -1, -1));

        address_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(address_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 169, 184, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 213, 1152, -1));

        product_details.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        product_details.setText("Product Details:");
        getContentPane().add(product_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, -1, -1));

        pid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pid.setText("Product Id");
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 268, -1, -1));

        pid_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pid_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pid_inputActionPerformed(evt);
            }
        });
        getContentPane().add(pid_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 265, 70, -1));

        pname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pname.setText("Product Name");
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 268, -1, -1));

        pname_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(pname_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 265, 150, -1));

        rate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rate.setText("Rate");
        getContentPane().add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 268, -1, -1));

        rate_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(rate_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 265, 109, -1));

        quantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quantity.setText("Quantity");
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 268, -1, -1));

        quantity_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(quantity_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 265, 107, -1));

        description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        description.setText("Description");
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 268, -1, -1));

        description_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(description_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 265, 222, -1));

        add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1074, 303, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 342, 1152, -1));

        billing_table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        billing_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(billing_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 357, 600, 180));

        calculation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calculation.setText("Calculation Details");
        getContentPane().add(calculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total.setText("Total");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        paid_amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paid_amount.setText("Paid Amount");
        getContentPane().add(paid_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, -1, -1));

        return_amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        return_amount.setText("Return Amount");
        getContentPane().add(return_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, -1));

        total_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(total_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 210, -1));

        paid_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paid_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paid_inputActionPerformed(evt);
            }
        });
        getContentPane().add(paid_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 210, -1));

        return_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        return_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_inputActionPerformed(evt);
            }
        });
        getContentPane().add(return_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 210, -1));

        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 400, 90, -1));

        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 450, -1, -1));

        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 90, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new billing().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inputActionPerformed
        // TODO add your handling code here:
        String name = name_input.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from buyer where name like '" + name + "%'");
            if (rs.next()) {
                name_input.setText(rs.getString(1));
                contact_input.setText(rs.getString(2));
                email_input.setText(rs.getString(3));
                address_input.setText(rs.getString(4));
            } else {
                contact_input.setText("");
                email_input.setText("");
                address_input.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_name_inputActionPerformed

    private void contact_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_inputActionPerformed
        // TODO add your handling code here:
        String contactNo = contact_input.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from buyer where contactNo like '" + contactNo + "%'");
            if (rs.next()) {
                name_input.setText(rs.getString(1));
                contact_input.setText(rs.getString(2));
                email_input.setText(rs.getString(3));
                address_input.setText(rs.getString(4));
            } else {
                name_input.setText("");
                email_input.setText("");
                address_input.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_contact_inputActionPerformed

    private void pid_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pid_inputActionPerformed
        // TODO add your handling code here:
        String pId = pid_input.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from product where pId like '" + pId + "%'");
            if (rs.next()) {
                pname_input.setText(rs.getString(2));
                rate_input.setText(rs.getString(3));
                quantity_input.setText("1");
                description_input.setText(rs.getString(4));
            } else {
                pname_input.setText("");
                rate_input.setText("");
                quantity_input.setText("");
                description_input.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pid_inputActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        int price = Integer.parseInt(rate_input.getText());
        int quantity = Integer.parseInt(quantity_input.getText());
        int total = price * quantity;
        DefaultTableModel model = (DefaultTableModel) billing_table.getModel();
        model.addRow(new Object[]{pname_input.getText(), description_input.getText(), price, quantity, total});
        finalTotal = finalTotal + total;
        String finalTotal1 = String.valueOf(finalTotal);
        total_input.setText(finalTotal1);

    }//GEN-LAST:event_addActionPerformed

    private void return_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_return_inputActionPerformed

    private void paid_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paid_inputActionPerformed
        // TODO add your handling code here:
        String paidAmount = paid_input.getText();
        int z = Integer.parseInt(paidAmount);
        finalTotal = z - finalTotal;
        String finalTotal1 = String.valueOf(finalTotal);
        return_input.setText(finalTotal1);
        return_input.setEditable(false);
    }//GEN-LAST:event_paid_inputActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String name = name_input.getText();
        String contactNo = contact_input.getText();
        String email = email_input.getText();
        String address = address_input.getText();

        String path = "C:\\Users\\hinab\\OneDrive\\Desktop\\My Docs\\Internships\\Main Flow Services and Technologies\\PROJECTS\\Billing Management System\\Bill_pdf\\";
        String fileName = name + " " + datei.getText().replaceAll("[^a-zA-Z0-9\\s]", "_") + ".pdf";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + fileName));
            doc.open();

            Paragraph paragraph1 = new Paragraph("                                       BTech Days(Billing Management system)\n                                       Contact Number:(+91)7201059632\n\n");
            doc.add(paragraph1);

            Paragraph paragraph2 = new Paragraph("Date: " + datei.getText() + "\nTime: " + timei.getText()
                    + "\n\nBuyer Details :\nName: " + name
                    + "\nContact No.: " + contactNo
                    + "\nE-mail: " + email
                    + "\nAddress: " + address + "\n\n");
            doc.add(paragraph2);

            PdfPTable tbl = new PdfPTable(5);
            tbl.addCell("Name");
            tbl.addCell("Description");
            tbl.addCell("Rate");
            tbl.addCell("Quantity");
            tbl.addCell("Sub Total");
            for (int i = 0; i < billing_table.getRowCount(); i++) {
                String n = billing_table.getValueAt(i, 0).toString();
                String d = billing_table.getValueAt(i, 1).toString();
                String r = billing_table.getValueAt(i, 2).toString();
                String q = billing_table.getValueAt(i, 3).toString();
                String s = billing_table.getValueAt(i, 4).toString();
                tbl.addCell(n);
                tbl.addCell(d);
                tbl.addCell(r);
                tbl.addCell(q);
                tbl.addCell(s);
            }
            doc.add(tbl);

            Paragraph paragraph3 = new Paragraph("\nBilling Details:\nTotal: " + total_input.getText()
                    + "\nPaid Amount: " + paid_input.getText()
                    + "\nReturn Amount: " + return_input.getText()
                    + "\n\nThanks You for Visiting! Please Come Again.\nBtech Days");
            doc.add(paragraph3);

            JOptionPane.showMessageDialog(null, "Bill Generated Succcessfully!");
            setVisible(false);
            new billing().setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
        doc.close();
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel address;
    private javax.swing.JTextField address_input;
    private javax.swing.JLabel background;
    private javax.swing.JLabel billing_ani;
    private javax.swing.JLabel billing_icon;
    private javax.swing.JTable billing_table;
    private javax.swing.JLabel buyer_details;
    private javax.swing.JLabel calculation;
    private javax.swing.JButton close;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField contact_input;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel datei;
    private javax.swing.JLabel description;
    private javax.swing.JTextField description_input;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email_input;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel paid_amount;
    private javax.swing.JTextField paid_input;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField pid_input;
    private javax.swing.JLabel pname;
    private javax.swing.JTextField pname_input;
    private javax.swing.JLabel product_details;
    private javax.swing.JLabel quantity;
    private javax.swing.JTextField quantity_input;
    private javax.swing.JLabel rate;
    private javax.swing.JTextField rate_input;
    private javax.swing.JButton reset;
    private javax.swing.JLabel return_amount;
    private javax.swing.JTextField return_input;
    private javax.swing.JButton save;
    private javax.swing.JLabel time_label;
    private javax.swing.JLabel timei;
    private javax.swing.JLabel total;
    private javax.swing.JTextField total_input;
    // End of variables declaration//GEN-END:variables
}
