/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hinab
 */
import javax.swing.JOptionPane;

public class home extends javax.swing.JFrame {

    public int z = 0;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        New_Buyer.setVisible(false);
        Update_Buyer.setVisible(false);
        Buyer_Details.setVisible(false);
        Delete_Buyer.setVisible(false);
        new_product.setVisible(false);
        Update_Product.setVisible(false);
        product_details.setVisible(false);
        delete_product.setVisible(false);
        billing.setVisible(false);
        logout.setVisible(false);
        close_application.setVisible(false);
        New_Buyer_text.setVisible(false);
        Update_Buyer_text.setVisible(false);
        Buyer_Details_text.setVisible(false);
        Delete_Buyer_text.setVisible(false);
        new_product_text.setVisible(false);
        Update_Product_text.setVisible(false);
        product_details_text.setVisible(false);
        delete_product_text.setVisible(false);
        billing_text.setVisible(false);
        logout_text.setVisible(false);
        close_application_text.setVisible(false);
        z = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hide = new javax.swing.JButton();
        New_Buyer = new javax.swing.JButton();
        Update_Buyer = new javax.swing.JButton();
        Buyer_Details = new javax.swing.JButton();
        Delete_Buyer = new javax.swing.JButton();
        new_product = new javax.swing.JButton();
        Update_Product = new javax.swing.JButton();
        product_details = new javax.swing.JButton();
        delete_product = new javax.swing.JButton();
        billing = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        close_application = new javax.swing.JButton();
        New_Buyer_text = new javax.swing.JLabel();
        Update_Buyer_text = new javax.swing.JLabel();
        Buyer_Details_text = new javax.swing.JLabel();
        Delete_Buyer_text = new javax.swing.JLabel();
        product_details_text = new javax.swing.JLabel();
        new_product_text = new javax.swing.JLabel();
        Update_Product_text = new javax.swing.JLabel();
        delete_product_text = new javax.swing.JLabel();
        billing_text = new javax.swing.JLabel();
        logout_text = new javax.swing.JLabel();
        close_application_text = new javax.swing.JLabel();
        home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 700));
        setMinimumSize(new java.awt.Dimension(1366, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/control hide and show.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 22, 80, -1));

        New_Buyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new buyer.png"))); // NOI18N
        New_Buyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                New_BuyerComponentShown(evt);
            }
        });
        New_Buyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_BuyerActionPerformed(evt);
            }
        });
        getContentPane().add(New_Buyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, -1));

        Update_Buyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update buyer.png"))); // NOI18N
        Update_Buyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Update_BuyerComponentShown(evt);
            }
        });
        getContentPane().add(Update_Buyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 80, -1));

        Buyer_Details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buyer details.png"))); // NOI18N
        Buyer_Details.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Buyer_DetailsComponentShown(evt);
            }
        });
        getContentPane().add(Buyer_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 80, -1));

        Delete_Buyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete buyer.png"))); // NOI18N
        Delete_Buyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Delete_BuyerComponentShown(evt);
            }
        });
        getContentPane().add(Delete_Buyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 80, -1));

        new_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        new_product.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                new_productComponentShown(evt);
            }
        });
        new_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_productActionPerformed(evt);
            }
        });
        getContentPane().add(new_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 80, -1));

        Update_Product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update product.png"))); // NOI18N
        Update_Product.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Update_ProductComponentShown(evt);
            }
        });
        getContentPane().add(Update_Product, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 80, -1));

        product_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/details product.png"))); // NOI18N
        product_details.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                product_detailsComponentShown(evt);
            }
        });
        getContentPane().add(product_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 80, -1));

        delete_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete product.png"))); // NOI18N
        delete_product.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                delete_productComponentShown(evt);
            }
        });
        getContentPane().add(delete_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 80, -1));

        billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing.png"))); // NOI18N
        billing.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                billingComponentShown(evt);
            }
        });
        getContentPane().add(billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 80, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                logoutComponentShown(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 80, -1));

        close_application.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        close_application.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_applicationActionPerformed(evt);
            }
        });
        getContentPane().add(close_application, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, 80, -1));

        New_Buyer_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        New_Buyer_text.setText("New Buyer");
        getContentPane().add(New_Buyer_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        Update_Buyer_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update_Buyer_text.setText("Update Buyer");
        getContentPane().add(Update_Buyer_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        Buyer_Details_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Buyer_Details_text.setText("Buyer Details");
        getContentPane().add(Buyer_Details_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        Delete_Buyer_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Delete_Buyer_text.setText("Delete Buyer");
        getContentPane().add(Delete_Buyer_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 80, -1));

        product_details_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        product_details_text.setText("Product Details");
        getContentPane().add(product_details_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        new_product_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        new_product_text.setText("New Product");
        getContentPane().add(new_product_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        Update_Product_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update_Product_text.setText("Update Product");
        getContentPane().add(Update_Product_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));

        delete_product_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delete_product_text.setText("Delete Product");
        getContentPane().add(delete_product_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, -1, -1));

        billing_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        billing_text.setText("Billing");
        getContentPane().add(billing_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 37, -1));

        logout_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout_text.setText("Logout");
        getContentPane().add(logout_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, -1, -1));

        close_application_text.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        close_application_text.setText("Close Application");
        getContentPane().add(close_application_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 100, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1370, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void New_BuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_BuyerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_BuyerActionPerformed

    private void new_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_productActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // TODO add your handling code here:
        if (z == 0) {
            try {
                Thread.sleep(100);
                New_Buyer.setVisible(true);
                New_Buyer_text.setVisible(true);
                z = 1;
            } catch (InterruptedException e) {
            }
        } else {
            New_Buyer.setVisible(false);
            New_Buyer_text.setVisible(false);
            Update_Buyer.setVisible(false);
            Update_Buyer_text.setVisible(false);
            Buyer_Details.setVisible(false);
            Buyer_Details_text.setVisible(false);
            Delete_Buyer.setVisible(false);
            Delete_Buyer_text.setVisible(false);
            new_product.setVisible(false);
            new_product_text.setVisible(false);
            Update_Product.setVisible(false);
            Update_Product_text.setVisible(false);
            product_details.setVisible(false);
            product_details_text.setVisible(false);
            delete_product.setVisible(false);
            delete_product_text.setVisible(false);
            billing.setVisible(false);
            billing_text.setVisible(false);
            logout.setVisible(false);
            logout_text.setVisible(false);
            close_application.setVisible(false);
            close_application_text.setVisible(false);
            z = 0;
        }
    }//GEN-LAST:event_hideMouseClicked

    private void New_BuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_New_BuyerComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            Update_Buyer.setVisible(true);
            Update_Buyer_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_New_BuyerComponentShown

    private void Update_BuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Update_BuyerComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            Buyer_Details.setVisible(true);
            Buyer_Details_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Update_BuyerComponentShown

    private void Buyer_DetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Buyer_DetailsComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            Delete_Buyer.setVisible(true);
            Delete_Buyer_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Buyer_DetailsComponentShown

    private void Delete_BuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Delete_BuyerComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            new_product.setVisible(true);
            new_product_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Delete_BuyerComponentShown

    private void new_productComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_new_productComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            Update_Product.setVisible(true);
            Update_Product_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_new_productComponentShown

    private void Update_ProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Update_ProductComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            product_details.setVisible(true);
            product_details_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Update_ProductComponentShown

    private void product_detailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_product_detailsComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            delete_product.setVisible(true);
            delete_product_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_product_detailsComponentShown

    private void delete_productComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_delete_productComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            billing.setVisible(true);
            billing_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_delete_productComponentShown

    private void billingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_billingComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            logout.setVisible(true);
            logout_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_billingComponentShown

    private void logoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logoutComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(100);
            close_application.setVisible(true);
            close_application_text.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logoutComponentShown

    private void close_applicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_applicationActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close this application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_close_applicationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buyer_Details;
    private javax.swing.JLabel Buyer_Details_text;
    private javax.swing.JButton Delete_Buyer;
    private javax.swing.JLabel Delete_Buyer_text;
    private javax.swing.JButton New_Buyer;
    private javax.swing.JLabel New_Buyer_text;
    private javax.swing.JButton Update_Buyer;
    private javax.swing.JLabel Update_Buyer_text;
    private javax.swing.JButton Update_Product;
    private javax.swing.JLabel Update_Product_text;
    private javax.swing.JButton billing;
    private javax.swing.JLabel billing_text;
    private javax.swing.JButton close_application;
    private javax.swing.JLabel close_application_text;
    private javax.swing.JButton delete_product;
    private javax.swing.JLabel delete_product_text;
    private javax.swing.JButton hide;
    private javax.swing.JLabel home;
    private javax.swing.JButton logout;
    private javax.swing.JLabel logout_text;
    private javax.swing.JButton new_product;
    private javax.swing.JLabel new_product_text;
    private javax.swing.JButton product_details;
    private javax.swing.JLabel product_details_text;
    // End of variables declaration//GEN-END:variables
}
