/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginapp;

/**
 *
 * @author hinab
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        
        txtusername.setBackground(new java.awt.Color(255, 255, 255, 255));
        txtpassword.setBackground(new java.awt.Color(255, 255, 255, 255));
        seen.setVisible(false);  // 👁️ Show "seen" icon
        hide.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        Remember = new javax.swing.JCheckBox();
        forget = new javax.swing.JLabel();
        dont = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        sign = new javax.swing.JButton();
        seen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/items/bg.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 83, 22));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 83, 21));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 210, -1));

        txtusername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 210, -1));

        login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login.setText("LOGIN");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        Remember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Remember.setForeground(new java.awt.Color(255, 255, 255));
        Remember.setText("Remember password");
        Remember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RememberActionPerformed(evt);
            }
        });
        getContentPane().add(Remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        forget.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forget.setForeground(new java.awt.Color(255, 255, 255));
        forget.setText("Forget password?");
        getContentPane().add(forget, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, 18));

        dont.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dont.setForeground(new java.awt.Color(255, 255, 255));
        dont.setText("Don't have an account?");
        getContentPane().add(dont, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        hide.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        hide.setForeground(new java.awt.Color(255, 255, 255));
        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/items/hide.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 30, 30));

        sign.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sign.setText("SIGN UP");
        getContentPane().add(sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 90, 30));

        seen.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        seen.setForeground(new java.awt.Color(255, 255, 255));
        seen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/items/show.png"))); // NOI18N
        seen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seenMouseClicked(evt);
            }
        });
        getContentPane().add(seen, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 30, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/items/bg.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1820, 960));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void RememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RememberActionPerformed

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // TODO add your handling code here:
        txtpassword.setEchoChar((char) 0); 

        // Toggle button visibility
        hide.setVisible(false);
        hide.setEnabled(false);
        seen.setVisible(true);
        seen.setEnabled(true);
    }//GEN-LAST:event_hideMouseClicked

    private void seenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seenMouseClicked
        // TODO add your handling code here:
        txtpassword.setEchoChar((char) 8226); 

        // Toggle button visibility
        hide.setVisible(true);
        hide.setEnabled(true);
        seen.setVisible(false);
        seen.setEnabled(false);
    }//GEN-LAST:event_seenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Remember;
    private javax.swing.JLabel dont;
    private javax.swing.JLabel forget;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton login;
    private javax.swing.JLabel seen;
    private javax.swing.JButton sign;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
